Update index.js with new standards for NodeJS
/mnt/c/esrhost/blue/esrhost/node_modules/run-php/index.js:142

RunPHP = Proxy.create({
^                                                                                                                                                                                                                                TypeError: Proxy.create is not a function
at Object.<anonymous> (/mnt/c/esrhost/blue/esrhost/node_modules/run-php/index.js:142:16)
at Module._compile (module.js:635:30)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)

As of the new versions of NodeJS, the correct syntax for Proxy is "new Proxy({}, {} );".

I edited the file on my end and confirmed that it's working properly with the new syntax.